defaults: &defaults
  host: 'localhost'
  port: 5672
  exchange: 'thundercats.messages'
  vhost: '/'
  user: 'guest'
  password: 'guest'
  log_level: 2
  log_filename: rabbitmq.log
  log_age: daily

development:
  <<: *defaults

staging:
  host: 'xxxxxx-xxxx'
  port: 5672
  exchange: 'thundercats.messages'
  vhost: '/'
  user: 'tygra'
  password: 'tygra123'
  log_level: 2
  log_filename: rabbitmq.log
  log_age: daily

test:
  <<: *defaults
  host: 'localhost'

production:
  host: ['x.x.x.x', 'x.x.x.x']
  port: 5672
  exchange: 'thundercats.messages'
  vhost: '/'
  user: 'tygra'
  password: 'tygra123'
  log_level: 2
  log_filename: rabbitmq.log
  log_age: daily
